[package]
name = "async-graphql-relay-example"
version = "0.1.0"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2018"

[dependencies]
async-graphql = "3.0.1"
actix-web = "3.3.2"
async-graphql-actix-web = "2.8.5"
async-graphql-relay = { path = "../" }