[package]
name = "async-graphql-relay-example"
version = "0.1.0"
authors = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition = "2024"

[dependencies]
async-graphql = "7"
actix-web = "4.11.0"
async-graphql-actix-web = "7.0.17"
async-graphql-relay = { path = "../", features = ["sea-orm"] }
